services:
  chorestar:
    image: ghcr.io/notfixingit3/chorestar:dev
    container_name: chorestar
    ports:
      - "8282:80"
    volumes:
      - ./data:/app/data
    networks:
      - groundzero
    restart: unless-stopped

networks:
  groundzero:
    external: true
    name: groundzero_lan
